name: CI

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Hack around https://github.com/actions/checkout/issues/290
        run: |
          git fetch --tags --force

      - name: Install and run Luacheck
        uses: nebularg/actions-luacheck@v1
        with:
          args: "--no-color -q"
          annotate: warning

      - name: Update CurseForge Translations
        # Run only for beta or release tags (skip alpha)
        if: startsWith(github.ref, 'refs/tags/') && (contains(github.ref, '-beta') || !contains(github.ref, '-alpha'))
        run: ./update_translations.sh
        env:
          CF_API_KEY: ${{ secrets.CURSE_API_TOKEN }}
      # - name: Generate Changelog
      #   run: ./generate_changelog.sh

      - name: Install LibEQOL
        uses: R41z0r/LibEQOL@v1.0.0
        with:
          destination: EnhanceQoL/libs

      - name: Create Package and release
        if: startsWith(github.ref, 'refs/tags/')
        uses: BigWigsMods/packager@v2
        env:
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          CF_API_KEY: ${{ secrets.CURSE_API_TOKEN }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI }}
